# Generated by Django 3.2.9 on 2021-11-17 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='review_posts',
        ),
    ]
