# Generated by Django 3.2.9 on 2021-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('규모', models.CharField(max_length=50)),
                ('병원', models.CharField(max_length=50)),
                ('보철물', models.CharField(max_length=50)),
                ('최저가', models.CharField(max_length=50)),
                ('최고가', models.CharField(max_length=50)),
                ('소재지', models.CharField(max_length=50)),
                ('지역', models.CharField(max_length=50)),
                ('구', models.CharField(max_length=50)),
            ],
        ),
    ]
